- name: Deploy landing page
  hosts: loadbalancers
  sudo: yes
  gather_facts: no 

  tasks:
    - name: Remove old files
      command: rm -rf /opt/www

    - name: Uploading files
      copy: src=./../../www dest=/opt owner=wordie group=wordie mode=0644 force=yes directory_mode=0655