- hosts: wordie_nodes
  sudo: yes
  serial: 1

  pre_tasks:
    - name: Disable the host
      set_fact: disabled=true

    - name: Copy nginx configuration
      template: src=roles/nginx/templates/default.conf dest=/etc/nginx/conf.d/default.conf
      delegate_to: "{{ item }}"
      with_items: groups.loadbalancers

    - name: Reload nginx configuration
      service: name=nginx state=reloaded
      delegate_to: "{{ item }}"
      with_items: groups.loadbalancers

  tasks:
    - { include: "roles/java-service/tasks/update.yaml", service_name: wordie, http_port: 3000 }

  post_tasks:
    - name: Enable the host
      set_fact: disabled=false

    - name: Copy nginx configuration
      template: src=roles/nginx/templates/default.conf dest=/etc/nginx/conf.d/default.conf
      delegate_to: "{{ item }}"
      with_items: groups.loadbalancers

    - name: Reload nginx configuration
      service: name=nginx state=reloaded
      delegate_to: "{{ item }}"
      with_items: groups.loadbalancers
